### PR TITLE
Allow elasticsearch 7

### PR DESCRIPTION
**Pull request by creddy**
Ready to merge

### CODE REVIEW

**Comment by creddy** [comment]
cc @jjun14 @ishaanhired @eatspaint @z4zebin We're testing out the newer version of elastic search. Tagging ya so you are aware

**Comment by eatspaint** [comment]
Hey @z4zebin just checking so I have context when reviewing this: Are we looking to merge these changes, or were we requested just to keep us in the loop on whats going on? If it's the former, would you mind updating the PR description (because the big "DO NOT MERGE" has me confused 😂 )

**Review by eatspaint — APPROVED** [review]
I don't have a lot of context here, but I'll approve so the work isn't blocked.

**Comment by z4zebin** [comment]
Ready to merge

**Review by ddiachkov — APPROVED** [review]

**Pull request merged**
