### PR TITLE
Feature/clauses

### PR DESCRIPTION
**Pull request by agius**
This will allow a lot more flexibility in chainable syntax, as well as DRYing up the parsers & options for flexible methods like `.where`

Commentary welcome.

### CODE REVIEW

**Comment by agius** [comment]
Here's the syntax I've got so far:

```ruby
Stretchy.search
  .match('all_match')
  .match(match_field: 'match_field_string')
  .match.not('all_not_match')
  .match.not(not_match_field: 'not_match_field_string')
  .where(
    must_string_field: 'must_string',
    does_not_exist_field: nil,
    must_terms: [:must_symbol_in_array, 9001, 'must_string_in_array_terms'],
    must_time_range: (Time.now - (3*60))..Time.now
  )
  .where.range(:min_field, min: 9000)
  .where.range(:max_field, max: 150000)
  .where.geo(:geo_location_field,
    distance: '27km',
    lat: 32.1,
    lng: 48.3
  )
  .where.not.geo(:excluded_geo_field,
    distance: '34mi',
    lat: 81.1,
    lng: 27.7
  )
  .where.not(
    does_exist_field: nil,
    must_not_string_field: 'must_not_string',
    must_not_terms: ['must_not_string_in_array', :must_not_symbol_in_array, 1001],
    must_not_range: 28..32
  )
``` 

@christospappas proposed renaming `.match` to `.fulltext`, and showed off some interesting language from [Mongoid's query builder](http://mongoid.org/en/mongoid/docs/querying.html) .

The more feedback I get, the better. The whole point of this gem is to have an _amazing_ developer UX for searching with Elastic. I know what I like, but I want all of you to love it, too @hired/developers . I want every method and what it does to be _insanely_ obvious & as intuitive as possible.

**Comment by jkarmel** [comment]
I agree with @christospappas <https://github.com/christospappas>, .fulltext
is three more characters but 10X the clarity

**Comment by agius** [comment]
Sold! :+1: I used `match` because that's what it's called in Elastic, and I hadn't thought of a better name. `.fulltext` is more clear.

**Comment by heythisisnate** [comment]
Some of the match options might make more sense or be more rememberable if they were changed to be more like english. I.e instead of `does_exist_field` it could be `field_exists`, and instead of `must_string_field` it could be like `field_must_be`

**Comment by agius** [comment]
For this refactor, I was looking mostly at `.where(field: nil)` and `.where.not(field: nil)` , kind of the way ActiveRecord handles it. Do you think it's worth adding something like `.exists(:field)` / `.exists.not(:field)` ?

**Comment by heythisisnate** [comment]
I do like that.

**Pull request merged**
