### PR TITLE
Add Sort support

### PR DESCRIPTION
**Pull request by leandrocp**
Based on ElastiSearch Sort, it'll add a "sort" attribute into body request.

I would open an Issue to discuss this feature, but the code was quick to write and a PR is better to show it working :)

Let me know if there's something wrong or missing.

### CODE REVIEW

**Comment by leandrocp** [comment]
@agius any news about this merge request ?

**Comment by agius** [comment]
@leandrocp Heya! Sorry I dropped the ball on this. Thanks so much for the PR! TBH, I thought we had implemented that during some internal customization or other, but I see that never made it here to the open source version. 

Looks pretty good to me - is this rebased to the ES5 version? If not, plz do, then should be merge-able this week.

**Comment by fedefa** [comment]
+1

**Comment by leandrocp** [comment]
@fedefa I'm not using this lib anymore, but I think it's ready to be merged.

@agius care to take a look ? may I do something to help ?

**Pull request closed without merging**
